### ISSUE TITLE
Missing workflow images

### ISSUE THREAD

**Issue by AndreaGuarracino** [YaoZhou89/TGG#1]
Hi, there are multiple missing images in the markdown files. The links are broken as they point to a local folder. Here are a few of them:

in https://github.com/YaoZhou89/TGG/blob/main/1.Genome_assembly/1.contig/Readme.md
![image-20220103182607789](/Users/zhiyangzhang/Library/Application Support/typora-user-images/image-20220103182607789.png)

in https://github.com/YaoZhou89/TGG/blob/main/1.Genome_assembly/2.scaffold/Readme.md
![image-20220103183236565](/Users/zhiyangzhang/Library/Application Support/typora-user-images/image-20220103183236565.png)

in https://github.com/YaoZhou89/TGG/blob/main/2.Genome_annotation/Readme.md
![image-20220101234140544](/Users/zhiyangzhang/Library/Application Support/typora-user-images/image-20220101234140544.png)

in https://github.com/YaoZhou89/TGG/blob/main/4.Graph_pangenome/1.construction_graph_genome/Readme.md
![image-20220102154738977](/Users/zhiyangzhang/Library/Application Support/typora-user-images/image-20220102154738977.png)

**Comment by YaoZhou89** [comment]
Thanks for pointing these out! We have updated these figures.

**Comment by YaoZhou89** [comment]
> Hi, there are multiple missing images in the markdown files. The links are broken as they point to a local folder. Here are a few of them:
> 
> in https://github.com/YaoZhou89/TGG/blob/main/1.Genome_assembly/1.contig/Readme.md ![image-20220103182607789](/Users/zhiyangzhang/Library/Application Support/typora-user-images/image-20220103182607789.png)
> 
> in https://github.com/YaoZhou89/TGG/blob/main/1.Genome_assembly/2.scaffold/Readme.md ![image-20220103183236565](/Users/zhiyangzhang/Library/Application Support/typora-user-images/image-20220103183236565.png)
> 
> in https://github.com/YaoZhou89/TGG/blob/main/2.Genome_annotation/Readme.md ![image-20220101234140544](/Users/zhiyangzhang/Library/Application Support/typora-user-images/image-20220101234140544.png)
> 
> in https://github.com/YaoZhou89/TGG/blob/main/4.Graph_pangenome/1.construction_graph_genome/Readme.md ![image-20220102154738977](/Users/zhiyangzhang/Library/Application Support/typora-user-images/image-20220102154738977.png)

Thanks for pointing these out! We have updated these figures.

**Comment by AndreaGuarracino** [comment]
Thank you for the quickness!
