### ISSUE TITLE
How to quantify SVs when constructing a GRM for SVs

### ISSUE THREAD

**Issue by StellaXia** [YaoZhou89/TGG#11]
Dear Dr. Zhou,

Thanks a lot for this fantastic work!
I wonder how did you quantify structural variations when constructing a GRM for SVs.

Many thanks!

Sincerely,
Stella.

**Comment by YaoZhou89** [comment]
I am unsure whether you are referring to generating the numeric format for SVs. If so, it is the same as SNPs.

**Comment by StellaXia** [comment]
> I am unsure whether you are referring to generating the numeric format for SVs. If so, it is the same as SNPs.

**Comment by StellaXia** [comment]
Many thanks Dr. Zhou!
