### ISSUE TITLE
Missing code/scripts for the `Genome_assembly` part

### ISSUE THREAD

**Issue by AndreaGuarracino** [YaoZhou89/TGG#2]
Hi, the `1.Genome_asembly/1.contig` part reports that

```
Flye, Hicanu and Hifiasm are used to assemble primary genome. GALA is used to fillter the potential miss-assembly regions. WGS is manual software intergrated in pipeline.
```

but I am not able to find all the code/scripts about it. For example, I see that a script called `draft_comp.sh` is missing, I don't see where `flye`, `canu`, `gala` are called, etc...

I state that I am a newbie with snakemake, and I apologize if this is the problem.

**Comment by YaoZhou89** [comment]
As the assembly tools are under fast development, we did not include the primary assembly code in this Snakemake file. It would be better to follow each assembler's official updates. The draft_comp.sh will be generated when we run the GALA pipeline. Here is the GALA pipeline for assembly: https://github.com/ganlab/gala

**Comment by AndreaGuarracino** [comment]
A bit unexpected. For reproducibility, it would be enough to just specify the commit versions for all the tools.

Anyway, thank you for the answer!

**Comment by YaoZhou89** [comment]
Actually, we tried to assemble these genomes using different assemblers at the beginning, and we learned the GALA pipeline later. Therefore, we do not include the primary assembler in this Snakemake file. I hope I've clarified your concerns this time. For the concerns of reproducibility, the three assemblers should be easy to use and you can follow the description in our manuscript. Then you can use these assemblies as input for the GALA pipeline.

**Comment by Johnsonzcode** [comment]
Dear @YaoZhou89 , How to install WGS or get the binary? It is useful when build pan-genome. Thank you in advance.

**Comment by OatDesign** [comment]
The WGS source code and binary are available at https://github.com/YaoZhou89/WGSc

**Comment by Johnsonzcode** [comment]
@zhoulab-ibcas Thank you so much!
