### ISSUE TITLE
关于使用vcf构图的问题

### ISSUE THREAD

**Issue by zhoudreames** [YaoZhou89/TGG#3]
您好，我在您公布的TGG1.1 vcf数据集中看到所有的变异位点都被merge成一个样本名（图一）,但是我看到有些构建vg图是包含所有的样本信息在vcf文件里面的，我想咨询下您，这两种方法有什么区别呢？为什么把多个样本的变异全部集中在一个样本集合内呢？
图1：TGG1.1 vcf
![image](https://user-images.githubusercontent.com/54714639/175450758-ebc584ad-f567-48c4-b74b-22b27ee64b85.png)
图2：human vg vcf文件
![image](https://user-images.githubusercontent.com/54714639/175450963-b9dfe283-b6d4-42bb-8cde-c7df8ef417fb.png)

**Comment by YaoZhou89** [comment]
我们参考的他们这个流程：https://github.com/vgteam/giraffe-sv-paper/tree/master/scripts/sv
这里他们有步是remove info.

**Comment by zhoudreames** [comment]
谢谢您的回复~ 我还有个小问题，我使用giraffe进行比对时速度很慢，可能比BWA要慢5~6倍，您们有没有这种情况发生呢？
