### ISSUE TITLE
Question about dedup merged SV

### ISSUE THREAD

**Issue by YiBenqiu** [YaoZhou89/TGG#4]
Hello, Mr. Zhou!
    I had a question when I read your code about dedup merged SV. Is this step necessary? Does it mean that if I do long-reads sequencing (HiFi or ONT) on some individuals, I also need to do short-reads sequencing (>20x) on them? This ensures that I can use their short reads for redup after merging SVs?
![df4858d3a10bcb5700910cf4583db37](https://user-images.githubusercontent.com/57091259/180728953-23608e55-465a-425b-ae42-6ce4d374e406.jpg)

**Comment by YaoZhou89** [comment]
Hi, this step removes duplicated SVs (might be due to the differences among callers for the same SV). The individuals with 20x short reads in our study were different from the individuals with long reads.
