### ISSUE TITLE
SV identified with 706  accessions

### ISSUE THREAD

**Issue by zhoudreames** [YaoZhou89/TGG#5]
In your method, Genotypes of Structural variants (SVs) in 706 accessions with following code:
```
multigrmpy.py -i /public10/home/sci0011/projects/tomato2/08_paragraph/02_vcf/SV.paragraph.vcf -m /public10/home/sci0011/projects/tomato2/08_paragraph/01_bam/samples_${sample}.txt -r ~/data/ref/SL5.0/SL5.0_chr_number.fa -o . --threads 64
```
but how to gain the file "SV.paragraph.vcf" ?

**Comment by YaoZhou89** [comment]
it is the SV set we used for constructing the TGG1.0. There are likely some SVs that failed to meet the requirement of the paragraph, therefore we filtered out these SVs (nine SVs if I remember correctly).
