### ISSUE TITLE
how to  jointly estimate the heritability with different variants set

### ISSUE THREAD

**Issue by zhoudreames** [YaoZhou89/TGG#6]
In your pipeline, the heritability assessment with a single variant set was provided， but I want to analyze categories of genetic variants jointly following your article, can you provide me with a more detailed code? thanks~

**Comment by YaoZhou89** [comment]
We used the multiple GRMs (--mgrm) when we estimated the h2 by using LDAK. see: https://dougspeed.com/reml-analysis/

**Comment by zhoudreames** [comment]
thanks~
