### ISSUE TITLE
Without prepare_gene_expression.R file files

### ISSUE THREAD

**Issue by zhoudreames** [YaoZhou89/TGG#7]
In your pipeline,  The  prepare_gene_expression.R script is missing in 5.Genetic_analysis, can you provide this code? Thanks~

**Comment by YaoZhou89** [comment]
We have already uploaded the script. Please see: https://github.com/YaoZhou89/TGG/blob/main/5.Genetic_analysis/scripts/prepare_gene_expression.R

**Comment by zhoudreames** [comment]
Thanks~

**Comment by zhoudreames** [comment]
Can you provide me with two test files to do it? thanks ~ 
For example, dat and ID files:
dat =read.table("/public10/home/sci0010/project/00_new_tomato/02.kallisto/sample_reverse_trans",head=T)
ID = read.table("332.txt",head=F)

**Comment by zhoudreames** [comment]
in your article, Raw expression levels were normalized with quantile–quantile normalization， whether the raw expression levels is the gene counts? Thanks~

**Comment by YaoZhou89** [comment]
We calculated the expression in TPM using kallisto.

**Comment by zhoudreames** [comment]
Thanks~
